import type { NextPage } from "next";
import Head from "next/head";
import { BsLinkedin } from "react-icons/bs";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Riccardo
          <br />
          Tornesello
        </h1>
        <h2 className={styles.subTitle}>Landing page under construction</h2>
        <a className={styles.linkedin}>
          <BsLinkedin />
          Linkedin
        </a>
      </main>
    </div>
  );
};

export default Home;
