import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { BsEnvelopeFill, BsGithub, BsLinkedin } from "react-icons/bs";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [showEmail, setShowEmail] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.titleContainer}>
          <span>{"<"}</span>
          <h1 className={styles.title}>
            Riccardo
            <br />
            Tornesello
          </h1>
          <span className={styles.bottom}>{"/>"}</span>
        </div>
        <h2 className={styles.subTitle}>
          <span className={styles.underline}>Website under construction</span>
        </h2>
        <div className={styles.socialContainer}>
          <a
            className={styles.socialButton}
            style={{ backgroundColor: "#0077b5" }}
          >
            <BsLinkedin />
            Linkedin
          </a>
          <a
            className={styles.socialButton}
            style={{ backgroundColor: "#171515" }}
          >
            <BsGithub />
            GitHub
          </a>
          <a
            className={styles.socialButton}
            style={{ backgroundColor: "#219ebc", width: showEmail ? 500 : 0 }}
            onClick={() => {
              setShowEmail(true)
            }}
          >
            <BsEnvelopeFill />
            {showEmail ? "riccardo.tornesello@gmail.com" : "Email"}
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
